# Generated by Django 4.0.3 on 2022-03-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type_name', models.CharField(max_length=255)),
                ('distance', models.FloatField()),
                ('beds', models.PositiveSmallIntegerField()),
                ('baths', models.PositiveSmallIntegerField()),
                ('url', models.URLField()),
                ('price_pcm', models.PositiveIntegerField()),
                ('price_pw', models.PositiveIntegerField()),
                ('available_date', models.DateField()),
                ('deposit', models.PositiveIntegerField()),
            ],
        ),
    ]
