# Generated by Django 4.0.3 on 2022-03-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_rightmove_id_alter_property_available_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='available_date',
            field=models.DateField(),
        ),
    ]
