# Generated by Django 4.0.3 on 2022-03-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_property_furnished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='available_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='deposit',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
